# Generated by Django 5.1.4 on 2024-12-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='main_image',
            field=models.ImageField(blank=True, default='media/no_photo.png', null=True, upload_to='media/', verbose_name='Главное изображение'),
        ),
    ]
